### ISSUE TITLE
build error: is CHANGES.rst missing when installing via pip?

### ISSUE THREAD

**Issue by philpot** [c-bata/outlier-utils#2]
## there was no problem when building from the zip

$ sudo -H pip install outlier-utils
Collecting outlier-utils
  Using cached outlier_utils-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-gmoeex/outlier-utils/setup.py", line 8, in <module>
        CHANGES = open(os.path.join(BASE_PATH, 'CHANGES.rst')).read()
    IOError: [Errno 2] No such file or directory: '/private/tmp/pip-build-gmoeex/outlier-utils/CHANGES.rst'

**Comment by c-bata** [comment]
Thank you for reporting! I fix it.

**Comment by c-bata** [comment]
@philpot I fixed this error and release to pypi.
https://pypi.python.org/pypi/outlier_utils
